'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace Solution

    Public Partial Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ExportCallback control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ExportCallback As Global.DevExpress.Web.ASPxCallback

        ''' <summary>
        ''' MyGridExporter control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MyGridExporter As Global.DevExpress.Web.ASPxGridViewExporter

        ''' <summary>
        ''' MyGrid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MyGrid As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' btnExportPDF control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnExportPDF As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnExportXLS control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnExportXLS As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btnExportRTF control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btnExportRTF As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' response_btn control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected response_btn As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' ASPxLoadingPanel1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxLoadingPanel1 As Global.DevExpress.Web.ASPxLoadingPanel
    End Class
End Namespace
